---
title: Include-code-files Extension For Quarto
filters:
  - include-code-files
---

Include code from files in code blocks.

``````{.markdown filename="document.qmd"}
---
title: "Include-code-files Example"
filters:
  - include-code-files
---

```{.python include="_snippets/hello_world.py"}
```
``````

Adapted from <https://github.com/pandoc/lua-filters/blob/master/include-code-files/include-code-files.lua> and written by [Bruno BEAUFILS](https://github.com/b3).


## Installing

```bash
quarto add SamEdwardes/include-code-files
```

This will install the extension under the `_extensions` subdirectory. If you're using version control, you will want to check in this directory.

## Using

To use the include-code-files filter add it to your documents yaml front matter:

```yaml
---
title: "My doc"
filters:
  - include-code-files
---
```

With the include-code-files filter you can include code snippets directly from a file using `include`. For example, you may have a python script like this:

```{.python filename="_snippets/hello_world.py" code-line-numbers="true" include="_snippets/hello_world.py"}
```

To render this file in a code chunk use the `include` attribute:

``````markdown
```{.python include="_snippets/hello_world.py"}
```
``````

```{.python include="_snippets/hello_world.py"}
```

This can be combined with other quarto attributes like `filename` and/or `code-line-numbers`:

``````markdown
```{.python filename="hello_world.py" include="_snippets/hello_world.py"}
```
``````

```{.python filename="hello_world.py" include="_snippets/hello_world.py"}
```

This can be combined with other quarto attributes like `filename`:

``````markdown
```{.python filename="hello_world.py" code-line-numbers="true"}
```
``````

```{.python  include="_snippets/hello_world.py" code-line-numbers="true"}
```


## Example

Here is the source code for a minimal example: [README.qmd](README.qmd).
